### ISSUE TITLE
Ingress pathing issue(s)

### ISSUE THREAD

**Issue by AAllport** [LocalBytes/localdeck-config#13]
There's been a change somewhere which has brought the addon to it's knees... investigating

**Comment by AAllport** [comment]
Attempt:

```sh
#!/usr/bin/with-contenv bashio
set +u

export NUXT_FILES_DIR=$(bashio::config 'esphome_dir')
export NUXT_APP_BASE_URL="$(bashio::addon.ingress_entry)"
export NUXT_PUBLIC_BASE_URL="$(bashio::addon.ingress_entry)"
export NUXT_APP_BUILD_ASSETS_DIR="$(bashio::addon.ingress_entry)/_nuxt"

export NUXT_API_TOKEN=${SUPERVISOR_TOKEN}

node ./server/index.mjs
```

Result:
✅ - Index Loads
✅ - Assets Load
❗ - API route 404ing

**Comment by AAllport** [comment]
Attempt:
```sh
#!/usr/bin/with-contenv bashio
set +u

export NUXT_FILES_DIR=$(bashio::config 'esphome_dir')
#export NUXT_APP_BASE_URL="$(bashio::addon.ingress_entry)"
export NUXT_PUBLIC_BASE_URL="$(bashio::addon.ingress_entry)"
export NUXT_APP_BUILD_ASSETS_DIR="$(bashio::addon.ingress_entry)/_nuxt"

export NUXT_API_TOKEN=${SUPERVISOR_TOKEN}

node ./server/index.mjs
```

Result:
❗ - Index fails (but "go back" works)
✅ - Assets Load
✅ - API Routes

**Comment by AAllport** [comment]
Current behaviour
https://github.com/LocalBytes/localdeck-config/assets/3750120/d41a664c-ae32-425f-8111-da4437c66b2e

**Comment by AAllport** [comment]
I think there's something in the deps-changes here - 7f1fb737
Especially given there was a gap between that and it's parent (8347dba8)

Will try drilling into it tomorrow

**Comment by bushbrother** [comment]
Following ...

**Comment by AAllport** [comment]
So we've got a working set of dependencies.
We have a minor issue with one of the deps not linking correctly when running inside the CI

I'm just seeing whether a generic `pnpm up -r` will break things...

Ideally, we'd find exactly which dep was causing the break, but we can look at that later since we have a working set.

**Comment by AAllport** [comment]
Looks like we're good, will be releasing 0.2.2 🔜
