### ISSUE TITLE
Issue when reopening previously saved config

### ISSUE THREAD

**Issue by AAllport** [LocalBytes/localdeck-config#30]
Some [users ](https://forum.mylocalbytes.com/d/58)are experiencing difficulties with configurations not persisting across saves...

**Comment by benchieng** [comment]
Hi! I'm bengx from the forums. I messed around with the yaml file and I'm not sure what happened but the values starting sticking between localdeck configurator instances again. I will upload both copies of yaml here for your reference.
[localdeck-fcea38.zip](https://github.com/user-attachments/files/16334420/localdeck-fcea38.zip)

**Comment by AAllport** [comment]
Just for some added context... we're working on making the issue(s) a little more visible when things like validation errors occour via #29 
Eg, if a malformed config is detected, it'll allow you to see what it's seeing and where the error is occurring, etc

**Comment by joshcliffejones** [comment]
Hello! Its homeautomationnutter from the LocalBytes forum (https://forum.mylocalbytes.com/d/58-localdeck-configurator-suggestion)

As requested, please see the current config for my localdeck which is currently working. But if I go back to the localdeck configurator, the configurator shows it as a blank device as far as its concerned.

![localdeck-configurator](https://github.com/user-attachments/assets/90aaad81-1fb8-4d9c-b6fb-8551c080bed1)

[localdeck-2e2988.zip](https://github.com/user-attachments/files/16384296/localdeck-2e2988.zip)

Many thanks in advanced! :)

**Comment by AAllport** [comment]
Thankyou both!
That'll be really helpful for debugging

**Comment by AKTheKnight** [comment]
Can confirm I'm seeing this too. And I think there might be two things going on:


The first issue is the GET response to `editor` seems to be failing to parse the correct button from the yaml and is then calling it `undefined`.

![image](https://github.com/user-attachments/assets/cb6415dc-d3ea-4a28-9d3a-5cc4dbfc1dc5)

In the yaml the above is on button 19.

It also seems to be failing to parse button 20 correctly which should be bound to `light.alex_bedside_lamp`. This was setup in the configurator too on a previous save.

My yaml is attached, and I'll do a reset later on today to see if I can work out at what point this stops working


[localdeck-fce9fc.zip](https://github.com/user-attachments/files/16424928/localdeck-fce9fc.zip)

**Comment by AAllport** [comment]
So we don't actually re-parse the yaml to figure out which button goes where...
Main reason is so we can do _fancy_ things like Virtual Components
https://github.com/LocalBytes/localdeck-config/blob/9fa3704d7e8937e87561d747afbc43a770fdb94b/packages/localdeck-components/src/utils/compression.ts#L16-L25

The config gets deflated then b64'd
https://github.com/LocalBytes/localdeck-config/blob/9fa3704d7e8937e87561d747afbc43a770fdb94b/packages/localdeck-components/src/utils/compression.ts#L16-L25

So, the likelihood is something is going wrong in the save phase... I'm just not sure what.
Additionally, I'm struggling to replicate this, which is frustrating!

I know the same issue cropped up in the forums here - https://forum.mylocalbytes.com/d/50
