### ISSUE TITLE
HA Integration: Entity list formatting needs some spaces

### ISSUE THREAD

**Issue by AKTheKnight** [LocalBytes/localdeck-config#34]
If I have a person in HA called Alex, then they're displayed in the dropdown Entity list as `Alexperson.alex`:
![image](https://github.com/user-attachments/assets/e15edb0e-7ebd-44ce-9dc4-7dc87ac4414c)

I feel like this could possible do with some formatting to add some spacing between the display name and the actual HA entity id.

Maybe a space or a `|`?

**Comment by AAllport** [comment]
This appears to be a regression... there should be a line-break.
Will fix 🔜

**Comment by AAllport** [comment]
Ahh, this is an issue when nothing is in the entity box.

![image](https://github.com/user-attachments/assets/89c248da-de45-4508-9207-d84210def405)

When you start typing, you should see it highlight the text as it's found

![image](https://github.com/user-attachments/assets/ff93df5d-cbee-44fb-90d1-2aa45ad5a459)

**Comment by AAllport** [comment]
Fixed in b1c5c02
