### ISSUE TITLE
Configurator not working

### ISSUE THREAD

**Issue by Jhonattan-Souza** [LocalBytes/localdeck-config#35]
![image](https://github.com/user-attachments/assets/21c661bb-c892-485f-a726-f5c8ce87103e)

Generated code from this config
![image](https://github.com/user-attachments/assets/fa7214f0-73c7-4253-b9b3-5afb47a1e271)

I am trying to configure localdeck , but i`m unable to install it

**Comment by AAllport** [comment]
Hi @Jhonattan-Souza,

We've seen this a few times. If you can go to ESPHome -> 3 dots menu -> Clean Build Files, then try again, you should be good!
